### ISSUE TITLE
iOS 9: jerky scrolling on text chat screen when there is a full list of messages

### ISSUE THREAD

**Issue by jvalli** [opentok/textchat-acc-pack#209]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/opentok/textchat-acc-pack/blob/develop/README.md) 
- [x] I have searched [existing issues](https://github.com/opentok/textchat-acc-pack/issues?utf8=%E2%9C%93&q=is%3Aissue+sort%3Acreated-desc+) and **this is not a duplicate**.

### General information

- Library version(s): 2.0.0-beta3
- iOS/Android/Browser version(s): iOS 9
- Devices/Simulators/Machine affected: iPhone/iPad/Simulator 
- Reproducible in the demo project? (Yes/No): Yes
- Related issues: No

#### Expected behavior

> Once a new message is listed the screen, the list needs to scroll down smoothly up to the bottom.

#### Actual behavior

> There is a jerky scrolling of the text chats list when the screen is full of messages listed.

#### Steps to reproduce

> 1.- Go to Text Chats Screen
> 2.- Write a few chats to fully complete the screen of message
> 3.- Notice the scroll animation when a new message is displayed

#### Sample project

>OTTextChatAccPackKit

**Comment by Lucashuang0802** [comment]
This seems to be a bug from iOS 9. Keep it as a record here.
